version: '3.8'
services:
  jupyter:
    image: "jupyter/pyspark-notebook:latest"
    container_name: pylatam2021
    user: root
    ports:
      - "8888:8888"
    volumes:
      - "./work:/home/jovyan/work"